### ISSUE TITLE
Issue with sources-GS test

### ISSUE THREAD

**Issue by bobonis** [Gekkio/mooneye-gb#49]
Hello,

I'm facing a problem with this test and I need your insight!
At **test_fe00:** , it appears that OAM is cleared with _call clear_oam_ , then DMA runs and the test compares the result with _ram_pattern_1_. Since OAM was cleared prior to DMA, it will never have the correct pattern, so you even have to remove the clear or reload the pattern before triggering the DMA.

I hope I didn't get the whole thing wrong! 
Keep up the great work!

**Comment by bobonis** [comment]
I went through your documentation again and I think that my initial assumption was wrong, as you clearly describe that DMA has access to EXTERNAL BUS or EXTERNAL VIDEO BUS. That means that I have to place address 0xFE00 on the external bus and perform the transfer from there. I will test it with my emulator as soon as possible and let you know!

**Comment by Gekkio** [comment]
Yeah, this is an intentional trap :sunglasses: The test catches emulators that incorrectly do a copy from OAM to OAM (= bytes don't change) or skip the transfer entirely.

Just like you suspected, the correct way to emulate this is to implement the different decoding scheme used by DMA, which in practice means 0xFE00 ends up on the external bus.
